### ISSUE TITLE
Crash when calling myke from myke

### ISSUE THREAD

**Issue by atetzner** [srettenmeier/myke#1]
When calling myke from inside a myke script, myke crashes

```
+ myke -f system/platform/ingress-controller bake --IMAGE_TAG=1.0.0-14.5de07cf
• ingress-controller/bake: Running
• Executing cmd: 
myke bake-pre-action --PROXY=$http_proxy
• ingress-controller/bake-pre-action: Running
• Executing cmd: 
myke download
• ingress-controller/download: Running
• Executing cmd: 
mkdir -p build/downloads

http_proxy= \
https_proxy= \
wget -O build/downloads/traefik \
  https://github.com/containous/traefik/releases/download/v1.5.4/traefik

panic: interface conversion: interp.VarValue is nil, not interp.StringVal

goroutine 1 [running]:
mvdan.cc/sh/interp.(*Runner).cmd(0xc4200b0000, 0x794080, 0xc420253550)
	/home/vagrant/workspace/go/src/mvdan.cc/sh/interp/interp.go:472 +0x24b3
mvdan.cc/sh/interp.(*Runner).stmtSync(0xc4200b0000, 0xc420373858)
	/home/vagrant/workspace/go/src/mvdan.cc/sh/interp/interp.go:416 +0x324
mvdan.cc/sh/interp.(*Runner).stmt(0xc4200b0000, 0xc420373858)
	/home/vagrant/workspace/go/src/mvdan.cc/sh/interp/interp.go:397 +0xca
mvdan.cc/sh/interp.(*Runner).stmts(0xc4200b0000, 0xc420388000, 0x2, 0x4, 0x0, 0x0, 0x0)
	/home/vagrant/workspace/go/src/mvdan.cc/sh/interp/interp.go:674 +0x51
mvdan.cc/sh/interp.(*Runner).Run(0xc4200b0000, 0x7933a0, 0xc4204cd840, 0x795080, 0xc4204ab8e0)
	/home/vagrant/workspace/go/src/mvdan.cc/sh/interp/interp.go:339 +0xe5
github.com/goeuro/myke/core.(*Execution).executeCmd(0xc420113b78, 0xc420150300, 0xb2, 0x0, 0x0)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/core/execution.go:140 +0x3bb
github.com/goeuro/myke/core.(*Execution).executeTask(0xc420113b78, 0x0, 0x0)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/core/execution.go:82 +0xd0
github.com/goeuro/myke/core.(*Execution).Execute.func1(0x1, 0xb, 0xc4201669d0, 0x1)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/core/execution.go:62 +0x45
github.com/goeuro/myke/core.retry(0xc420113ae0, 0xb, 0xc4201669d0)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/core/util.go:101 +0x40
github.com/goeuro/myke/core.(*Execution).Execute(0xc420113b78, 0xc4200aec80, 0xc4200aeb40)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/core/execution.go:61 +0x298
github.com/goeuro/myke/core.ExecuteQuery(0xc4200914d0, 0x7ffc9f1e4951, 0x8, 0x7ffc9f1e4951, 0x8, 0xc420054bd0, 0x0, 0x1, 0xc4200914a0, 0xc4200b8200, ...)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/core/execution.go:43 +0x1da
github.com/goeuro/myke/cmd.Run(0xc420096550, 0xc420054b50, 0x1, 0x1, 0xc4200ace30, 0xc4200acdc0)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/cmd/run.go:17 +0x223
github.com/goeuro/myke/cmd.Action(0xc420096550, 0xc420054b50, 0x1, 0x1, 0xc420054b50, 0x1)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/cmd/root.go:73 +0x11f
github.com/goeuro/myke/cmd.Exec(0xc42000c0b0, 0x1, 0x1, 0xc420113f78, 0xc42001e0b8)
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/cmd/root.go:47 +0x465
main.main()
	/home/vagrant/workspace/go/src/github.com/goeuro/myke/main.go:10 +0x6b
• ingress-controller/bake-pre-action: Failed, Took: 41.27044ms
⨯ error                     error=error running command: ingress-controller/bake-pre-action: exit status 2
• ingress-controller/bake: Failed, Took: 66.655099ms
⨯ error                     error=error running command: ingress-controller/bake: exit status 1
```

Issue is reproducible in my dev-box as well as on Jenkins build server (i³ ci-box).

For more information - e.g. the exact myke script - please contact me directly, as I can't post the scripts here.

**Comment by atetzner** [comment]
It seems as if the issue is triggered when you execute a task, that executes another task and the second task contains the placeholder `{{ .PROXY }}` - other placeholders are no problem.

```yaml
tasks
  taskA:
    cmd: |
      myke taskB

  taskB:
    cmd: |
      echo {{ .OTHER_VAR }} # No problem
      echo {{ .PROXY }} # Fails
```

I worked around this issue by replacing ``{{ .PROXY }}`` by `${PROXY}`
